#!/usr/bin/env python


import os,sys  # exit
import time   # time accounting
import getopt # command line parser
import numpy as np
import varsList
from os import environ
from ROOT import gSystem, gROOT, gApplication
from ROOT import TMVA, TFile, TTree, TCut, TString
from subprocess import call
from os.path import isfile

from keras.models import Sequential
from keras.layers.core import Dense
from keras.optimizers import Adam

from array import array
# Setup TMVA
TMVA.Tools.Instance()
TMVA.PyMethodBase.PyInitialize()
reader = TMVA.Reader("Color:!Silent")

iFile = str(sys.argv[1])
oFile = str(sys.argv[2])
wFile = str(sys.argv[3])



data = TFile.Open(iFile)

branches = {}

branches[  "AK4HTpMETpLepPt"            ] = array('f', [-999])
branches[  "minMleppBjet"               ] = array('f', [-999])
branches[  "mass_minBBdr"               ] = array('f', [-999])
branches[  "deltaR_lepBJet_maxpt"       ] = array('f', [-999])
branches[  "lepDR_minBBdr"              ] = array('f', [-999])
branches[  "centrality"                 ] = array('f', [-999])
branches[  "deltaEta_maxBB"             ] = array('f', [-999])
branches[  "aveCSVpt"                   ] = array('f', [-999])
branches[  "aveBBdr"                    ] = array('f', [-999])
branches[  "FW_momentum_0"              ] = array('f', [-999])
branches[  "FW_momentum_1"              ] = array('f', [-999])
branches[  "FW_momentum_2"              ] = array('f', [-999])
branches[  "FW_momentum_3"              ] = array('f', [-999])
branches[  "FW_momentum_4"              ] = array('f', [-999])
branches[  "FW_momentum_5"              ] = array('f', [-999])
branches[  "FW_momentum_6"              ] = array('f', [-999])
branches[  "mass_maxJJJpt"              ] = array('f', [-999])
branches[  "BJetLeadPt"                 ] = array('f', [-999])
branches[  "deltaR_minBB"               ] = array('f', [-999])
branches[  "minDR_lepBJet"              ] = array('f', [-999])
branches[  "MT_lepMet"                  ] = array('f', [-999])
branches[  "AK4HT"                      ] = array('f', [-999])
branches[  "hemiout"                    ] = array('f', [-999])
branches[  "theJetLeadPt"               ] = array('f', [-999])
branches[  "corr_met_singleLepCalc"     ] = array('f', [-999])
branches[  "leptonPt_singleLepCalc"     ] = array('f', [-999])
branches[  "mass_lepJets0"              ] = array('f', [-999])
branches[  "mass_lepJets1"              ] = array('f', [-999])
branches[  "mass_lepJets2"              ] = array('f', [-999])
branches[  "MT2bb"                      ] = array('f', [-999])
branches[  "mass_lepBJet0"              ] = array('f', [-999])
branches[  "mass_lepBJet_mindr"         ] = array('f', [-999])
branches[  "secondJetPt"                ] = array('f', [-999])
branches[  "fifthJetPt"                 ] = array('f', [-999])
branches[  "sixthJetPt"                 ] = array('f', [-999])
branches[  "PtFifthJet"                 ] = array('f', [-999])
branches[  "mass_minLLdr"               ] = array('f', [-999])
branches[  "mass_maxBBmass"             ] = array('f', [-999])
branches[  "deltaR_lepJetInMinMljet"    ] = array('f', [-999])
branches[  "deltaPhi_lepJetInMinMljet"  ] = array('f', [-999])
branches[  "deltaR_lepbJetInMinMlb"     ] = array('f', [-999])
branches[  "deltaPhi_lepbJetInMinMlb"   ] = array('f', [-999])
branches[  "M_allJet_W"                 ] = array('f', [-999])
branches[  "HT_bjets"                   ] = array('f', [-999])
branches[  "ratio_HTdHT4leadjets"       ] = array('f', [-999])
branches[  "csvJet3"                    ] = array('f', [-999])
branches[  "csvJet4"                    ] = array('f', [-999])
branches[  "thirdcsvb_bb"               ] = array('f', [-999])
branches[  "fourthcsvb_bb"              ] = array('f', [-999])
branches[  "NJets_JetSubCalc"           ] = array('f', [-999])
branches[  "HT_2m"                      ] = array('f', [-999])
branches[  "Sphericity"                 ] = array('f', [-999])
branches[  "Aplanarity"                 ] = array('f', [-999])

# branches[  "deltaR_minBB"     ] = array('f', [-999])
# branches[  "aveBBdr"          ] = array('f', [-999])
# branches[  "deltaEta_maxBB"   ] = array('f', [-999])
# branches[  "AK4HT"            ] = array('f', [-999])
# branches[  "centrality"       ] = array('f', [-999])
# branches[  "FW_momentum_2"    ] = array('f', [-999])
# branches[  "aveCSVpt"         ] = array('f', [-999])

# branches[  "minMleppBjet"     ] = array('f', [-999])
# branches[  "BJetLeadPt"       ] = array('f', [-999])
# branches[  "mass_maxJJJpt"    ] = array('f', [-999])
# branches[  "lepDR_minBBdr"    ] = array('f', [-999])
# branches[  "corr_met"         ] = array('f', [-999])
# branches[  "MT_lepMet"        ] = array('f', [-999])


reader.AddVariable(           "AK4HTpMETpLepPt",            branches[  "AK4HTpMETpLepPt"            ])
reader.AddVariable(           "minMleppBjet",               branches[  "minMleppBjet"               ])
reader.AddVariable(           "mass_minBBdr",               branches[  "mass_minBBdr"               ])
reader.AddVariable(           "deltaR_lepBJet_maxpt",       branches[  "deltaR_lepBJet_maxpt"       ])
reader.AddVariable(           "lepDR_minBBdr",              branches[  "lepDR_minBBdr"              ])
reader.AddVariable(           "centrality",                 branches[  "centrality"                 ])
reader.AddVariable(           "deltaEta_maxBB",             branches[  "deltaEta_maxBB"             ])
reader.AddVariable(           "aveCSVpt",                   branches[  "aveCSVpt"                   ])
reader.AddVariable(           "aveBBdr",                    branches[  "aveBBdr"                    ])
reader.AddVariable(           "FW_momentum_0",              branches[  "FW_momentum_0"              ])
reader.AddVariable(           "FW_momentum_1",              branches[  "FW_momentum_1"              ])
reader.AddVariable(           "FW_momentum_2",              branches[  "FW_momentum_2"              ])
reader.AddVariable(           "FW_momentum_3",              branches[  "FW_momentum_3"              ])
reader.AddVariable(           "FW_momentum_4",              branches[  "FW_momentum_4"              ])
reader.AddVariable(           "FW_momentum_5",              branches[  "FW_momentum_5"              ])
reader.AddVariable(           "FW_momentum_6",              branches[  "FW_momentum_6"              ])
reader.AddVariable(           "mass_maxJJJpt",              branches[  "mass_maxJJJpt"              ])
reader.AddVariable(           "BJetLeadPt",                 branches[  "BJetLeadPt"                 ])
reader.AddVariable(           "deltaR_minBB",               branches[  "deltaR_minBB"               ])
reader.AddVariable(           "minDR_lepBJet",              branches[  "minDR_lepBJet"              ])
reader.AddVariable(           "MT_lepMet",                  branches[  "MT_lepMet"                  ])
reader.AddVariable(           "AK4HT",                      branches[  "AK4HT"                      ])
reader.AddVariable(           "hemiout",                    branches[  "hemiout"                    ])
reader.AddVariable(           "theJetLeadPt",               branches[  "theJetLeadPt"               ])
reader.AddVariable(           "corr_met_singleLepCalc",     branches[  "corr_met_singleLepCalc"     ])
reader.AddVariable(           "leptonPt_singleLepCalc",     branches[  "leptonPt_singleLepCalc"     ])
reader.AddVariable(           "mass_lepJets0",              branches[  "mass_lepJets0"              ])
reader.AddVariable(           "mass_lepJets1",              branches[  "mass_lepJets1"              ])
reader.AddVariable(           "mass_lepJets2",              branches[  "mass_lepJets2"              ])
reader.AddVariable(           "MT2bb",                      branches[  "MT2bb"                      ])
reader.AddVariable(           "mass_lepBJet0",              branches[  "mass_lepBJet0"              ])
reader.AddVariable(           "mass_lepBJet_mindr",         branches[  "mass_lepBJet_mindr"         ])
reader.AddVariable(           "secondJetPt",                branches[  "secondJetPt"                ])
reader.AddVariable(           "fifthJetPt",                 branches[  "fifthJetPt"                 ])
reader.AddVariable(           "sixthJetPt",                 branches[  "sixthJetPt"                 ])
reader.AddVariable(           "PtFifthJet",                 branches[  "PtFifthJet"                 ])
reader.AddVariable(           "mass_minLLdr",               branches[  "mass_minLLdr"               ])
reader.AddVariable(           "mass_maxBBmass",             branches[  "mass_maxBBmass"             ])
reader.AddVariable(           "deltaR_lepJetInMinMljet",    branches[  "deltaR_lepJetInMinMljet"    ])
reader.AddVariable(           "deltaPhi_lepJetInMinMljet",  branches[  "deltaPhi_lepJetInMinMljet"  ])
reader.AddVariable(           "deltaR_lepbJetInMinMlb",     branches[  "deltaR_lepbJetInMinMlb"     ])
reader.AddVariable(           "deltaPhi_lepbJetInMinMlb",   branches[  "deltaPhi_lepbJetInMinMlb"   ])
reader.AddVariable(           "M_allJet_W",                 branches[  "M_allJet_W"                 ])
reader.AddVariable(           "HT_bjets",                   branches[  "HT_bjets"                   ])
reader.AddVariable(           "ratio_HTdHT4leadjets",       branches[  "ratio_HTdHT4leadjets"       ])
reader.AddVariable(           "csvJet3",                    branches[  "csvJet3"                    ])
reader.AddVariable(           "csvJet4",                    branches[  "csvJet4"                    ])
reader.AddVariable(           "thirdcsvb_bb",               branches[  "thirdcsvb_bb"               ])
reader.AddVariable(           "fourthcsvb_bb",              branches[  "fourthcsvb_bb"              ])
reader.AddVariable(           "NJets_JetSubCalc",           branches[  "NJets_JetSubCalc"           ])
reader.AddVariable(           "HT_2m",                      branches[  "HT_2m"                      ])
reader.AddVariable(           "Sphericity",                 branches[  "Sphericity"                 ])
reader.AddVariable(           "Aplanarity",                 branches[  "Aplanarity"                 ])

# reader.AddVariable(    "deltaR_minBB",   branches[  "deltaR_minBB"    ])
# reader.AddVariable(         "aveBBdr",   branches[  "aveBBdr"         ])
# reader.AddVariable(  "deltaEta_maxBB",   branches[  "deltaEta_maxBB"  ])
# reader.AddVariable(           "AK4HT",   branches[  "AK4HT"           ])
# reader.AddVariable(      "centrality",   branches[  "centrality"      ])
# reader.AddVariable(   "FW_momentum_2",   branches[  "FW_momentum_2"   ])
# reader.AddVariable(        "aveCSVpt",   branches[  "aveCSVpt"        ])
# reader.AddVariable(    "minMleppBjet",   branches[  "minMleppBjet"    ])
# reader.AddVariable(      "BJetLeadPt",   branches[  "BJetLeadPt"      ])
# reader.AddVariable(   "mass_maxJJJpt",   branches[  "mass_maxJJJpt"   ])
# reader.AddVariable(   "lepDR_minBBdr",   branches[  "lepDR_minBBdr"   ])
# reader.AddVariable(        "corr_met",   branches[  "corr_met"        ])
# reader.AddVariable(       "MT_lepMet",   branches[  "MT_lepMet"       ])

# Book methods
reader.BookMVA('PyKeras', TString(wFile))

theTree = data.Get('ljmet')

theTree.SetBranchAddress(           "AK4HTpMETpLepPt",            branches[  "AK4HTpMETpLepPt"            ])
theTree.SetBranchAddress(           "minMleppBjet",               branches[  "minMleppBjet"               ])
theTree.SetBranchAddress(           "mass_minBBdr",               branches[  "mass_minBBdr"               ])
theTree.SetBranchAddress(           "deltaR_lepBJet_maxpt",       branches[  "deltaR_lepBJet_maxpt"       ])
theTree.SetBranchAddress(           "lepDR_minBBdr",              branches[  "lepDR_minBBdr"              ])
theTree.SetBranchAddress(           "centrality",                 branches[  "centrality"                 ])
theTree.SetBranchAddress(           "deltaEta_maxBB",             branches[  "deltaEta_maxBB"             ])
theTree.SetBranchAddress(           "aveCSVpt",                   branches[  "aveCSVpt"                   ])
theTree.SetBranchAddress(           "aveBBdr",                    branches[  "aveBBdr"                    ])
theTree.SetBranchAddress(           "FW_momentum_0",              branches[  "FW_momentum_0"              ])
theTree.SetBranchAddress(           "FW_momentum_1",              branches[  "FW_momentum_1"              ])
theTree.SetBranchAddress(           "FW_momentum_2",              branches[  "FW_momentum_2"              ])
theTree.SetBranchAddress(           "FW_momentum_3",              branches[  "FW_momentum_3"              ])
theTree.SetBranchAddress(           "FW_momentum_4",              branches[  "FW_momentum_4"              ])
theTree.SetBranchAddress(           "FW_momentum_5",              branches[  "FW_momentum_5"              ])
theTree.SetBranchAddress(           "FW_momentum_6",              branches[  "FW_momentum_6"              ])
theTree.SetBranchAddress(           "mass_maxJJJpt",              branches[  "mass_maxJJJpt"              ])
theTree.SetBranchAddress(           "BJetLeadPt",                 branches[  "BJetLeadPt"                 ])
theTree.SetBranchAddress(           "deltaR_minBB",               branches[  "deltaR_minBB"               ])
theTree.SetBranchAddress(           "minDR_lepBJet",              branches[  "minDR_lepBJet"              ])
theTree.SetBranchAddress(           "MT_lepMet",                  branches[  "MT_lepMet"                  ])
theTree.SetBranchAddress(           "AK4HT",                      branches[  "AK4HT"                      ])
theTree.SetBranchAddress(           "hemiout",                    branches[  "hemiout"                    ])
theTree.SetBranchAddress(           "theJetLeadPt",               branches[  "theJetLeadPt"               ])
theTree.SetBranchAddress(           "corr_met_singleLepCalc",     branches[  "corr_met_singleLepCalc"     ])
theTree.SetBranchAddress(           "leptonPt_singleLepCalc",     branches[  "leptonPt_singleLepCalc"     ])
theTree.SetBranchAddress(           "mass_lepJets0",              branches[  "mass_lepJets0"              ])
theTree.SetBranchAddress(           "mass_lepJets1",              branches[  "mass_lepJets1"              ])
theTree.SetBranchAddress(           "mass_lepJets2",              branches[  "mass_lepJets2"              ])
theTree.SetBranchAddress(           "MT2bb",                      branches[  "MT2bb"                      ])
theTree.SetBranchAddress(           "mass_lepBJet0",              branches[  "mass_lepBJet0"              ])
theTree.SetBranchAddress(           "mass_lepBJet_mindr",         branches[  "mass_lepBJet_mindr"         ])
theTree.SetBranchAddress(           "secondJetPt",                branches[  "secondJetPt"                ])
theTree.SetBranchAddress(           "fifthJetPt",                 branches[  "fifthJetPt"                 ])
theTree.SetBranchAddress(           "sixthJetPt",                 branches[  "sixthJetPt"                 ])
theTree.SetBranchAddress(           "PtFifthJet",                 branches[  "PtFifthJet"                 ])
theTree.SetBranchAddress(           "mass_minLLdr",               branches[  "mass_minLLdr"               ])
theTree.SetBranchAddress(           "mass_maxBBmass",             branches[  "mass_maxBBmass"             ])
theTree.SetBranchAddress(           "deltaR_lepJetInMinMljet",    branches[  "deltaR_lepJetInMinMljet"    ])
theTree.SetBranchAddress(           "deltaPhi_lepJetInMinMljet",  branches[  "deltaPhi_lepJetInMinMljet"  ])
theTree.SetBranchAddress(           "deltaR_lepbJetInMinMlb",     branches[  "deltaR_lepbJetInMinMlb"     ])
theTree.SetBranchAddress(           "deltaPhi_lepbJetInMinMlb",   branches[  "deltaPhi_lepbJetInMinMlb"   ])
theTree.SetBranchAddress(           "M_allJet_W",                 branches[  "M_allJet_W"                 ])
theTree.SetBranchAddress(           "HT_bjets",                   branches[  "HT_bjets"                   ])
theTree.SetBranchAddress(           "ratio_HTdHT4leadjets",       branches[  "ratio_HTdHT4leadjets"       ])
theTree.SetBranchAddress(           "csvJet3",                    branches[  "csvJet3"                    ])
theTree.SetBranchAddress(           "csvJet4",                    branches[  "csvJet4"                    ])
theTree.SetBranchAddress(           "thirdcsvb_bb",               branches[  "thirdcsvb_bb"               ])
theTree.SetBranchAddress(           "fourthcsvb_bb",              branches[  "fourthcsvb_bb"              ])
theTree.SetBranchAddress(           "NJets_JetSubCalc",           branches[  "NJets_JetSubCalc"           ])
theTree.SetBranchAddress(           "HT_2m",                      branches[  "HT_2m"                      ])
theTree.SetBranchAddress(           "Sphericity",                 branches[  "Sphericity"                 ])
theTree.SetBranchAddress(           "Aplanarity",                 branches[  "Aplanarity"                 ])


# theTree.SetBranchAddress(    "deltaR_minBB",   branches[  "deltaR_minBB"    ])
# theTree.SetBranchAddress(         "aveBBdr",   branches[  "aveBBdr"         ])
# theTree.SetBranchAddress(  "deltaEta_maxBB",   branches[  "deltaEta_maxBB"  ])
# theTree.SetBranchAddress(           "AK4HT",   branches[  "AK4HT"           ])
# theTree.SetBranchAddress(      "centrality",   branches[  "centrality"      ])
# theTree.SetBranchAddress(   "FW_momentum_2",   branches[  "FW_momentum_2"   ])
# theTree.SetBranchAddress(        "aveCSVpt",   branches[  "aveCSVpt"        ])

# theTree.SetBranchAddress(    "minMleppBjet",   branches[  "minMleppBjet"    ])
# theTree.SetBranchAddress(      "BJetLeadPt",   branches[  "BJetLeadPt"      ])
# theTree.SetBranchAddress(   "mass_maxJJJpt",   branches[  "mass_maxJJJpt"   ])
# theTree.SetBranchAddress(   "lepDR_minBBdr",   branches[  "lepDR_minBBdr"   ])
# theTree.SetBranchAddress(        "corr_met",   branches[  "corr_met"        ])
# theTree.SetBranchAddress(       "MT_lepMet",   branches[  "MT_lepMet"       ])

target = TFile( oFile, "RECREATE" );
target.cd()
newTree = theTree.CloneTree(0);   
DNN = array('f', [0])
newTree.Branch( "DNN", DNN, "DNN/F" );

for i in range(theTree.GetEntries()):
#     print "i : ", i
    theTree.GetEntry(i)
    DNN[0] = reader.EvaluateMVA('PyKeras')
    newTree.Fill()



newTree.Write()
target.Close()
